language: php

sudo: false

php:
    - 7.2

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

notifications:
    email: false