language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit ./tests/

notifications:
    email: false